package com.linguaframe.job.domain.vo;

import java.math.BigDecimal;
import java.util.List;

public record NarrationEvidenceVo(
        String jobId,
        String status,
        int segmentCount,
        int totalCharacterCount,
        BigDecimal totalTimelineDurationSeconds,
        int timelineGapCount,
        BigDecimal timelineGapSeconds,
        boolean timelineHasOverlap,
        int voicePresetCount,
        String voiceSummary,
        String defaultVoice,
        boolean narrationAudioReady,
        int audioArtifactCount,
        String audioLayout,
        boolean timeAligned,
        boolean narratedVideoReady,
        int narratedVideoArtifactCount,
        String mixMode,
        BigDecimal duckingVolume,
        BigDecimal narrationVolume,
        int fadeDurationMs,
        String mixSettingsSource,
        int segmentMixOverrideCount,
        String segmentMixOverrideSummary,
        int mixKeyframeCount,
        String mixKeyframeLaneSummary,
        List<NarrationEvidenceCheckVo> checks,
        List<NarrationEvidenceLinkVo> safeLinks,
        List<String> packageEntries,
        List<String> safetyNotes
) {
    public NarrationEvidenceVo(
            String jobId,
            String status,
            int segmentCount,
            int totalCharacterCount,
            BigDecimal totalTimelineDurationSeconds,
            int timelineGapCount,
            BigDecimal timelineGapSeconds,
            boolean timelineHasOverlap,
            int voicePresetCount,
            String voiceSummary,
            String defaultVoice,
            boolean narrationAudioReady,
            int audioArtifactCount,
            String audioLayout,
            boolean timeAligned,
            boolean narratedVideoReady,
            int narratedVideoArtifactCount,
            String mixMode,
            BigDecimal duckingVolume,
            BigDecimal narrationVolume,
            int fadeDurationMs,
            String mixSettingsSource,
            int segmentMixOverrideCount,
            String segmentMixOverrideSummary,
            List<NarrationEvidenceCheckVo> checks,
            List<NarrationEvidenceLinkVo> safeLinks,
            List<String> packageEntries,
            List<String> safetyNotes
    ) {
        this(
                jobId,
                status,
                segmentCount,
                totalCharacterCount,
                totalTimelineDurationSeconds,
                timelineGapCount,
                timelineGapSeconds,
                timelineHasOverlap,
                voicePresetCount,
                voiceSummary,
                defaultVoice,
                narrationAudioReady,
                audioArtifactCount,
                audioLayout,
                timeAligned,
                narratedVideoReady,
                narratedVideoArtifactCount,
                mixMode,
                duckingVolume,
                narrationVolume,
                fadeDurationMs,
                mixSettingsSource,
                segmentMixOverrideCount,
                segmentMixOverrideSummary,
                0,
                "none",
                checks,
                safeLinks,
                packageEntries,
                safetyNotes
        );
    }
}
