package com.linguaframe.job.domain.vo;

import java.time.Instant;
import java.util.List;

public record ReviewedSubtitleWorkflowVo(
        String jobId,
        String videoId,
        String targetLanguage,
        Instant generatedAt,
        String overallStatus,
        String phase,
        String recommendedNextAction,
        int segmentCount,
        int missingTargetCount,
        int timingMismatchCount,
        Integer qualityScore,
        String qualityVerdict,
        int qualityIssueCount,
        int qualitySuggestedFixCount,
        int editedSegmentCount,
        int reviewedSegmentCount,
        int followupSegmentCount,
        int annotationCount,
        int reviewerNoteCount,
        Instant draftLastUpdatedAt,
        int generatedSubtitleArtifactCount,
        int reviewedSubtitleArtifactCount,
        boolean reviewedBurnedVideoAvailable,
        boolean handoffReady,
        List<ReviewedSubtitleWorkflowCheckVo> checks,
        List<ReviewedSubtitleWorkflowLinkVo> links,
        List<String> safetyNotes
) {
    public ReviewedSubtitleWorkflowVo(
            String jobId,
            String videoId,
            String targetLanguage,
            Instant generatedAt,
            String overallStatus,
            String phase,
            String recommendedNextAction,
            int segmentCount,
            int missingTargetCount,
            int timingMismatchCount,
            Integer qualityScore,
            String qualityVerdict,
            int qualityIssueCount,
            int qualitySuggestedFixCount,
            int editedSegmentCount,
            Instant draftLastUpdatedAt,
            int generatedSubtitleArtifactCount,
            int reviewedSubtitleArtifactCount,
            boolean reviewedBurnedVideoAvailable,
            boolean handoffReady,
            List<ReviewedSubtitleWorkflowCheckVo> checks,
            List<ReviewedSubtitleWorkflowLinkVo> links,
            List<String> safetyNotes
    ) {
        this(
                jobId,
                videoId,
                targetLanguage,
                generatedAt,
                overallStatus,
                phase,
                recommendedNextAction,
                segmentCount,
                missingTargetCount,
                timingMismatchCount,
                qualityScore,
                qualityVerdict,
                qualityIssueCount,
                qualitySuggestedFixCount,
                editedSegmentCount,
                editedSegmentCount,
                0,
                0,
                0,
                draftLastUpdatedAt,
                generatedSubtitleArtifactCount,
                reviewedSubtitleArtifactCount,
                reviewedBurnedVideoAvailable,
                handoffReady,
                checks,
                links,
                safetyNotes
        );
    }
}
