package com.linguaframe.operator.domain.vo;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;

public record DemoSessionCommandCenterVo(
        Instant generatedAt,
        String overallStatus,
        String phase,
        String recommendedNextAction,
        String primaryCommand,
        DemoSessionCommandCenterRunVo focusRun,
        DemoSessionCommandCenterRunVo activeRun,
        DemoSessionCommandCenterRunVo recommendedCompletedRun,
        List<DemoSessionCommandCenterPhaseVo> phases,
        List<DemoSessionCommandCenterActionVo> actions,
        List<DemoSessionCommandCenterEvidenceVo> evidenceLinks,
        String recoveryStatus,
        int recoverNowCount,
        int watchCount,
        int needsReviewCount,
        int readyCount,
        String recoveryRecommendedNextAction,
        DemoSessionRecoveryBoardActionVo recoveryPrimaryAction,
        List<DemoSessionRecoveryBoardLinkVo> recoveryLinks,
        String narrationProductionStatus,
        int narrationReadyCount,
        int narrationNeedsReviewCount,
        int narrationNeedsRenderCount,
        int narrationNeedsAuthoringCount,
        int narrationBlockedCount,
        int narrationNotApplicableCount,
        String narrationRecommendedNextAction,
        SessionNarrationProductionActionVo narrationPrimaryAction,
        List<SessionNarrationProductionLinkVo> narrationProductionLinks,
        String costControlStatus,
        BigDecimal costControlRecentEstimatedCostUsd,
        BigDecimal costControlDailyEstimatedCostUsd,
        int costControlFailedModelCallCount,
        String costControlRecommendedNextAction,
        DemoSessionCostControlActionVo costControlPrimaryAction,
        List<DemoSessionCostControlLinkVo> costControlLinks,
        BigDecimal estimatedCostUsd,
        int modelCallCount,
        int failedModelCallCount,
        BigDecimal failureRatePercent,
        long averageLatencyMs,
        int providerCacheHitCount,
        List<String> safetyNotes
) {
}
