package com.linguaframe.job.domain.enums;

public enum JobArtifactType {

    EXTRACTED_AUDIO,
    TRANSCRIPT_JSON,
    SUBTITLE_SRT,
    SUBTITLE_VTT,
    TARGET_SUBTITLE_JSON,
    TARGET_SUBTITLE_SRT,
    TARGET_SUBTITLE_VTT,
    REVIEWED_SUBTITLE_JSON,
    REVIEWED_SUBTITLE_SRT,
    REVIEWED_SUBTITLE_VTT,
    DUBBING_AUDIO,
    BURNED_VIDEO,
    DUBBED_VIDEO,
    REVIEWED_BURNED_VIDEO,
    WORKER_SUMMARY
}
