package com.linguaframe.job.domain.enums;

public enum LocalizationJobStage {

    WORKER_RECEIVED,
    WORKER_SMOKE,
    AUDIO_EXTRACTION,
    TRANSCRIPT_SUBTITLE_EXPORT,
    TARGET_SUBTITLE_EXPORT,
    TRANSLATION_QUALITY_EVALUATION,
    DUBBING_AUDIO_GENERATION,
    SUBTITLE_BURN_IN,
    ARTIFACT_SUMMARY,
    COMPLETED
}
